spring:
  application:
    name: devops
  datasource:
    url: ${DB_URL:jdbc:mysql://db:3306/mydb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none